const FavoritesActionTypes ={
    FETCH_FAVORITES_START : 'FETCH_FAVORITES_START',
    FETCH_FAVORITES_FAILURE : 'FETCH_FAVORITES_FAILURE',
    FETCH_ADD_FAVORITES : 'FETCH_ADD_FAVORITES'
}

export default FavoritesActionTypes;
